apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: logging
data:
  logstash.conf: |
    input {
      tcp {
        port => 5000
        code => json
        }
    }

    filter {
      mutate {
        remove_field => ["@version", "host" ]
      }
    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch.logging.svc.cluster.local:9200"]
        index => "fastapi-logs-%{+YYYY.MM.dd}"
      }
      stdout {
        code => rubydebug
      }
    }

