apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: logging
data:
  logstash.conf: |
    input {
      tcp {
        port => 5000
        codec => json
        }
    }

    filter {
      mutate {
        remove_field => ["@version", "host" ]
      }
    }
  logstash.yml: |
    queue.type: persisted
    queue.max_bytes: 512mb
    path.queue: /usr/share/logstash/data/queue
    path.dead_letter_queue: /usr/share/logstash/data/dead_letter_queue

    output {
      elasticsearch {
        hosts => ["http://elasticsearch.logging.svc.cluster.local:9200"]
        index => "fastapi-logs-%{+YYYY.MM.dd}"
      }
      stdout {
        codec => rubydebug
      }
    }
